name: sdk

on:
  push:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./src/sdk/package.json
          token: ${{ secrets.NPM_TOKEN }}
