openapi: 3.0.1
info:
  title: SpaceTraders Syndicate API
  description: spacetraders.io OpenAPI Spec
  version: 1.0.0
  contact:
    email: jaredlshort@gmail.com
servers:
  - url: https://api.spacetraders.io
    description: Production
  - url: https://staging.api.spacetraders.io
    description: Staging
paths:
  /users/{username}/token:
    $ref: ./paths/usersToken.yml
  /users/{username}:
    $ref: ./paths/users.yml
  /users/{username}/loans:
    $ref: ./paths/usersLoans.yml
  /users/{username}/loans/{loanId}:
    $ref: ./paths/usersLoansById.yml
  /game/systems/{symbol}/flight-plans:
    $ref: ./paths/gameSystemsFlightPlans.yml
  /game/loans:
    $ref: ./paths/gameLoans.yml
  /game/ships:
    $ref: ./paths/gameShips.yml
  /game/systems:
    $ref: ./paths/gameSystems.yml
  /game/status:
    $ref: ./paths/gameStatus.yml

components:
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
security:
- bearerAuth: []